{"includedArchiveIdentifiers":["HMError"],"interfaceLanguages":{"swift":[{"children":[{"children":[{"title":"Initializers","type":"groupMarker"},{"path":"\/documentation\/hmerror\/someerror\/init()","title":"init()","type":"init"},{"title":"Default Implementations","type":"groupMarker"},{"children":[{"title":"Operators","type":"groupMarker"},{"path":"\/documentation\/hmerror\/someerror\/!=(_:_:)","title":"static func != (Self, Self) -> Bool","type":"op"}],"path":"\/documentation\/hmerror\/someerror\/equatable-implementations","title":"Equatable Implementations","type":"symbol"},{"children":[{"title":"Instance Methods","type":"groupMarker"},{"path":"\/documentation\/hmerror\/someerror\/throw()","title":"func `throw`<Never>() throws(Self) -> Never","type":"method"},{"path":"\/documentation\/hmerror\/someerror\/throw(_:)","title":"func `throw`<Input, Never>(Input) throws(Self) -> Never","type":"method"}],"path":"\/documentation\/hmerror\/someerror\/error-implementations","title":"Error Implementations","type":"symbol"}],"path":"\/documentation\/hmerror\/someerror","title":"SomeError","type":"struct"},{"path":"\/documentation\/hmerror\/swift\/error\/throw()","title":"func `throw`<Never>() throws(Self) -> Never","type":"method"},{"path":"\/documentation\/hmerror\/swift\/error\/throw(_:)","title":"func `throw`<Input, Never>(Input) throws(Self) -> Never","type":"method"},{"title":"Error Coalescing","type":"groupMarker"},{"path":"\/documentation\/hmerror\/__(_:_:)-3h8k7","title":"func ¿? <Value, Error1>(@autoclosure () throws -> Value, () throws(Error1) -> Value) throws(Error1) -> Value","type":"op"},{"path":"\/documentation\/hmerror\/__(_:_:)-1sqz9","title":"func ¿? <Value, Error1>(@autoclosure () async throws -> Value, () async throws(Error1) -> Value) async throws(Error1) -> Value","type":"op"},{"path":"\/documentation\/hmerror\/__(_:_:)-6z1ub","title":"func ¿? <Success, Failure, NewFailure>(@autoclosure () async throws(Failure) -> Success, (Failure) -> NewFailure) async throws(NewFailure) -> Success","type":"op"},{"path":"\/documentation\/hmerror\/__(_:_:)-4puh3","title":"func ¿? <Success, Failure, NewFailure>(@autoclosure () throws(Failure) -> Success, (Failure) -> NewFailure) throws(NewFailure) -> Success","type":"op"},{"title":"Force Casting Errors","type":"groupMarker"},{"path":"\/documentation\/hmerror\/_!(_:_:)-1m4a0","title":"func ¿! <Value, Error>(@autoclosure () throws -> Value, Error.Type) throws(Error) -> Value","type":"op"},{"path":"\/documentation\/hmerror\/forcecasterror(to:_:)-39yeh","title":"func forceCastError<each Input, Value, Error>(to: Error.Type, (repeat each Input) throws -> Value) -> (repeat each Input) throws(Error) -> Value","type":"func"},{"path":"\/documentation\/hmerror\/_!(_:_:)-2tbvm","title":"func ¿! <Value, Error>(@autoclosure () async throws -> Value, Error.Type) async throws(Error) -> Value","type":"op"},{"path":"\/documentation\/hmerror\/forcecasterror(to:_:)-7uuo5","title":"func forceCastError<each Input, Value, Error>(to: Error.Type, (repeat each Input) async throws -> Value) -> (repeat each Input) async throws(Error) -> Value","type":"func"}],"path":"\/documentation\/hmerror","title":"HMError","type":"module"}]},"schemaVersion":{"major":0,"minor":1,"patch":2}}